#!/usr/bin/env node
/**
 * Generate the app's logo assets from a private brand lockup.
 *
 * Why this exists: this repository is a PUBLIC fork, and the InfoAnalytica lockup is a
 * company asset that must not appear in it. So every logo-bearing file the app builds
 * against is generated here and git-ignored, and the master lives at `ia_assets/logo.svg`,
 * also git-ignored. Nothing this script writes is ever committed.
 *
 * With the master present you get the real branding. Without it you get clearly-marked
 * neutral placeholders, so a fresh public clone still builds and runs.
 *
 *   node scripts/apply-brand.mjs          generate (placeholders if no master)
 *   node scripts/apply-brand.mjs --check  report what would happen, write nothing
 */

import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'fs'
import { dirname, resolve } from 'path'
import { tmpdir } from 'os'
import { fileURLToPath } from 'url'
import { createRequire } from 'module'
import { spawnSync } from 'child_process'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const MASTER = resolve(ROOT, 'ia_assets/logo.svg')
const CHECK = process.argv.includes('--check')

const OUT = {
  appFullLight: 'src/assets/logo-light-full.svg',
  appFullDark: 'src/assets/logo-dark-full.svg',
  appIconLight: 'src/assets/logo-light-icon.svg',
  appIconDark: 'src/assets/logo-dark-icon.svg',
  appFavicon: 'public/favicon.svg',
  docsFullLight: 'docs/logo/light-full.svg',
  docsFullDark: 'docs/logo/dark-full.svg',
  docsIconLight: 'docs/logo/light-icon.svg',
  docsIconDark: 'docs/logo/dark-icon.svg',
  docsFavicon: 'docs/favicon.svg',
  desktopIconSvg: 'build/icon.svg',
  desktopIconPng: 'build/icon.png',
  desktopIconIco: 'build/icon.ico',
}

/** Foreground for dark grounds — matches `--foreground` in the .dark theme block. */
const DARK_NEUTRAL = '#FAFAFA'

function write(rel, contents) {
  const abs = resolve(ROOT, rel)
  if (CHECK) return console.log(`  would write ${rel}`)
  // Identical content is left alone rather than rewritten. Otherwise every build bumps the
  // SVG's mtime, which makes the icon PNG look stale and re-launches Electron each time.
  if (existsSync(abs) && readFileSync(abs, 'utf8') === contents) {
    return console.log(`  ${rel} (unchanged)`)
  }
  mkdirSync(dirname(abs), { recursive: true })
  writeFileSync(abs, contents)
  console.log(`  ${rel}`)
}

// ---------------------------------------------------------------------------
// Real branding, derived from the master lockup
// ---------------------------------------------------------------------------

/*
 * The master is a 246x42 lockup of three groups: the mark (violet dot + dark bubble), the
 * gradient "info", the solid "analytica", and a tagline row along the bottom. They are
 * addressed by path index because the file is flat — there are no groups to select. That
 * makes the indices specific to THIS artwork, so the shape of the file is asserted below
 * rather than assumed; a new lockup should fail loudly instead of emitting scrambled glyphs.
 */
const EXPECTED_PATHS = 39
const GROUPS = {
  mark: [0, 1, 2],
  wordmark: [16, 17, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18],
  // Tagline paths (19-38) and their gradient bullets (3-6) are deliberately unused: the
  // tagline is 6px of a 42px frame, so at the ~30px the UI shows a lockup at, it renders
  // about 4px tall and reads as noise.
}

function parseMaster() {
  const svg = readFileSync(MASTER, 'utf8')
  const paths = svg.match(/<path\b[^>]*\/>/g) ?? []
  if (paths.length !== EXPECTED_PATHS) {
    throw new Error(
      `ia_assets/logo.svg has ${paths.length} paths, expected ${EXPECTED_PATHS}.\n` +
        `The lockup changed, so the path groups in scripts/apply-brand.mjs no longer match it.\n` +
        `Re-derive GROUPS against the new artwork before regenerating.`
    )
  }
  const gradients = Object.fromEntries(
    [...svg.matchAll(/<linearGradient id="(paint\d_linear_543_13049)"[\s\S]*?<\/linearGradient>/g)]
      .map((m) => [m[1], m[0]])
  )
  return { paths, gradients }
}

function build({ paths, gradients }, { indices, width, height, dark, note }) {
  let body = indices.map((i) => paths[i]).join('\n  ')
  if (dark) body = body.replaceAll('fill="#2D2D2D"', `fill="${DARK_NEUTRAL}"`)
  const used = [...new Set([...body.matchAll(/url\(#(paint\d_linear_543_13049)\)/g)].map((m) => m[1]))]
  const defs = used.map((id) => gradients[id]).join('\n    ')
  return (
    `<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" fill="none" ` +
    `xmlns="http://www.w3.org/2000/svg">\n` +
    `  <!-- GENERATED by scripts/apply-brand.mjs from ia_assets/logo.svg. Do not edit, and do\n` +
    `       not commit: this file carries a private company asset and is git-ignored.\n` +
    `       ${note} -->\n` +
    `  <defs>\n    ${defs}\n  </defs>\n  ${body}\n</svg>\n`
  )
}

/** Brand-gradient tile with the mark knocked out in white, for the desktop app icon. */
function desktopIcon({ paths }) {
  const S = 1024
  const pad = 0.19
  const scale = (S * (1 - 2 * pad)) / 42
  const off = S * pad
  const mark = GROUPS.mark
    .map((i) => paths[i])
    .join('\n    ')
    .replace(/fill="(#2D2D2D|url\(#paint\d_linear_543_13049\))"/g, 'fill="#FFFFFF"')
  return (
    `<svg width="${S}" height="${S}" viewBox="0 0 ${S} ${S}" xmlns="http://www.w3.org/2000/svg">\n` +
    `  <!-- GENERATED by scripts/apply-brand.mjs. Git-ignored (private company asset).\n` +
    `       A white tile would vanish into a light taskbar and the mark's own dark bubble would\n` +
    `       vanish into a dark one, so the tile carries the gradient and the mark goes white. -->\n` +
    `  <defs>\n` +
    `    <linearGradient id="tile" x1="0" y1="0" x2="${S}" y2="${S}" gradientUnits="userSpaceOnUse">\n` +
    `      <stop stop-color="#6C63FF"/><stop offset="1" stop-color="#BF59FE"/>\n` +
    `    </linearGradient>\n  </defs>\n` +
    `  <rect width="${S}" height="${S}" rx="${Math.round(S * 0.14)}" fill="url(#tile)"/>\n` +
    `  <g transform="translate(${off.toFixed(1)},${off.toFixed(1)}) scale(${scale.toFixed(4)})">\n` +
    `    ${mark}\n  </g>\n</svg>\n`
  )
}

// ---------------------------------------------------------------------------
// Placeholders, for a clone without the private master
// ---------------------------------------------------------------------------

const PLACEHOLDER_NOTE =
  'PLACEHOLDER. The private brand lockup is absent, so this is a neutral stand-in that ' +
  'keeps the build working. Drop the real lockup at ia_assets/logo.svg and re-run ' +
  '`pnpm brand` to replace it.'

function placeholder({ width, height, dark, label }) {
  const fg = dark ? DARK_NEUTRAL : '#2D2D2D'
  const glyph =
    `<rect x="1" y="1" width="${width - 2}" height="${height - 2}" rx="3" fill="none" ` +
    `stroke="${fg}" stroke-width="1.5" stroke-dasharray="4 3"/>` +
    (label
      ? `<text x="${width / 2}" y="${height / 2 + 4}" text-anchor="middle" fill="${fg}" ` +
        `font-family="monospace" font-size="11">${label}</text>`
      : '')
  return (
    `<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" fill="none" ` +
    `xmlns="http://www.w3.org/2000/svg">\n  <!-- ${PLACEHOLDER_NOTE} -->\n  ${glyph}\n</svg>\n`
  )
}

// ---------------------------------------------------------------------------
// Raster icon
// ---------------------------------------------------------------------------

/** Sizes packed into the .ico. 256 is the one Windows uses for large tiles. */
const ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]

/**
 * Pack already-encoded PNG buffers into a single .ico.
 *
 * Windows has accepted PNG-compressed icon entries since Vista, so each size goes in as its
 * own PNG rather than a BMP — which means no bitmap encoder is needed here.
 */
function packIco(images) {
  const HEADER = 6
  const ENTRY = 16
  const header = Buffer.alloc(HEADER)
  header.writeUInt16LE(0, 0) // reserved
  header.writeUInt16LE(1, 2) // 1 = icon
  header.writeUInt16LE(images.length, 4)

  let offset = HEADER + ENTRY * images.length
  const entries = images.map(({ size, data }) => {
    const e = Buffer.alloc(ENTRY)
    e.writeUInt8(size >= 256 ? 0 : size, 0) // 0 encodes 256
    e.writeUInt8(size >= 256 ? 0 : size, 1)
    e.writeUInt8(0, 2) // palette size, 0 for truecolour
    e.writeUInt8(0, 3) // reserved
    e.writeUInt16LE(1, 4) // colour planes
    e.writeUInt16LE(32, 6) // bits per pixel
    e.writeUInt32LE(data.length, 8)
    e.writeUInt32LE(offset, 12)
    offset += data.length
    return e
  })
  return Buffer.concat([header, ...entries, ...images.map((i) => i.data)])
}

/**
 * Render the icon SVG to `build/icon.png` (Linux/macOS) and `build/icon.ico` (Windows).
 *
 * The .ico matters more than it looks. Given only a PNG, electron-builder downloads a helper
 * "icons" bundle into %LOCALAPPDATA% to convert it — and on a corporate Windows box that
 * download fails with `EPERM ... rename icons-bundle-xxxx.tmp` when antivirus holds the
 * freshly-written temp file. Shipping a real .ico means the conversion never happens and that
 * whole failure mode disappears.
 *
 * Electron is already a devDependency and carries Chromium, so it does the rasterising and no
 * new dependency is added. If it cannot start (headless, no display) the build still works —
 * electron-builder falls back to the stock icon — so this warns and moves on.
 */
function rasterize(svgRel, pngRel, icoRel) {
  if (CHECK) return console.log(`  would rasterize ${svgRel} -> ${pngRel}, ${icoRel}`)
  // Launching Electron costs seconds, and this runs on every build. The icon only changes
  // when the lockup does, so skip it while both outputs are newer than the SVG.
  const svgAbs = resolve(ROOT, svgRel), pngAbs = resolve(ROOT, pngRel), icoAbs = resolve(ROOT, icoRel)
  if (
    existsSync(pngAbs) && existsSync(icoAbs) &&
    statSync(pngAbs).mtimeMs >= statSync(svgAbs).mtimeMs &&
    statSync(icoAbs).mtimeMs >= statSync(svgAbs).mtimeMs
  ) {
    return console.log(`  ${pngRel}, ${icoRel} (up to date)`)
  }
  // Kept out of the tree so it never shows up as an untracked file.
  const runner = resolve(mkdtempSync(resolve(tmpdir(), 'brand-')), 'rasterize.mjs')
  writeFileSync(
    runner,
    // Deliberately no top-level await and no `offscreen: true`. Both were tried and both make
    // Electron exit before it ever reaches whenReady, which looks identical to "no display" —
    // it just hangs to the timeout with nothing on stderr. `transparent: true` plus a
    // transparent body is what makes the tile's rounded corners come out clear (RGBA) rather
    // than boxed in white.
    // Deliberately captures once at 1024 and downsamples with nativeImage.resize rather than
    // opening a window per size: Windows enforces a minimum window size, so a 16x16
    // BrowserWindow cannot be captured at all.
    `import { app, BrowserWindow } from 'electron'
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
const args = process.argv.slice(2).filter((a) => !a.startsWith('-'))
const [svgPath, pngPath, outDir, sizeList] = args
const sizes = sizeList.split(',').map(Number)
app.disableHardwareAcceleration()
app.whenReady().then(async () => {
  const w = new BrowserWindow({ width: 1024, height: 1024, show: false, frame: false,
    transparent: true })
  const svg = readFileSync(svgPath, 'utf8')
  await w.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(
    '<body style="margin:0;background:transparent">' + svg + '</body>'))
  await new Promise((r) => setTimeout(r, 500))
  const img = await w.webContents.capturePage()
  // A hidden transparent window can hand back an empty or wrongly-sized bitmap instead of
  // throwing, which would write a blank PNG and ship an invisible app icon. Fail instead.
  const { width, height } = img.getSize()
  if (img.isEmpty() || width < 512 || height < 512) {
    throw new Error('capturePage returned ' + width + 'x' + height + ', expected 1024x1024')
  }
  writeFileSync(pngPath, img.toPNG())
  for (const s of sizes) {
    const scaled = img.resize({ width: s, height: s, quality: 'best' })
    if (scaled.isEmpty()) throw new Error('resize to ' + s + ' produced an empty image')
    writeFileSync(join(outDir, 'icon-' + s + '.png'), scaled.toPNG())
  }
  app.exit(0)
}).catch((err) => { console.error(String(err && err.message || err)); app.exit(1) })
`
  )
  // The electron package's main export is the path to its own executable when required from
  // plain Node, which is the only cross-platform way to find it: the binary is
  // dist/electron.exe on Windows, dist/electron on Linux, and inside a .app bundle on macOS.
  // Hardcoding the Linux path silently fell through to a bare "electron" that Windows cannot
  // resolve, so this failed as an ENOENT that looked like a 60-second hang.
  let electronBin
  try {
    electronBin = createRequire(import.meta.url)('electron')
  } catch {
    /* handled below as a missing binary */
  }
  if (typeof electronBin !== 'string' || !existsSync(electronBin)) {
    if (existsSync(pngAbs)) rmSync(pngAbs)
    return console.warn(
      `  ! cannot find the Electron binary, so ${pngRel}/${icoRel} were not generated.\n` +
        `    Run \`pnpm install\` and re-run \`pnpm brand\`. The app icon falls back to\n` +
        `    Electron's default until then; nothing else is affected.`
    )
  }

  // ELECTRON_RUN_AS_NODE is deleted rather than blanked. Windows treats an empty-string
  // variable as set, which would make the binary run as plain Node and never open a window.
  const env = { ...process.env }
  delete env.ELECTRON_RUN_AS_NODE

  const sizeDir = dirname(runner)

  // Timed out rather than left to block: with no display Electron waits instead of failing,
  // which would hang `pnpm build` on a headless machine.
  const res = spawnSync(
    electronBin,
    [
      runner,
      resolve(ROOT, svgRel),
      resolve(ROOT, pngRel),
      sizeDir,
      ICO_SIZES.join(','),
      '--disable-gpu',
      '--no-sandbox',
    ],
    { stdio: 'pipe', timeout: 60_000, env }
  )

  const sizeFiles = ICO_SIZES.map((size) => ({ size, path: resolve(sizeDir, `icon-${size}.png`) }))
  const haveAllSizes = sizeFiles.every((f) => existsSync(f.path))

  if (res.status === 0 && existsSync(pngAbs) && haveAllSizes) {
    mkdirSync(dirname(icoAbs), { recursive: true })
    writeFileSync(icoAbs, packIco(sizeFiles.map((f) => ({ size: f.size, data: readFileSync(f.path) }))))
    console.log(`  ${pngRel}`)
    console.log(`  ${icoRel} (${ICO_SIZES.join('/')}px)`)
  } else {
    // Drop both. A stale icon rendered from a different lockup, or a PNG with no matching .ico,
    // is worse than falling back to Electron's default — the .ico is what Windows reads, so a
    // mismatched pair ships the wrong art.
    if (existsSync(pngAbs)) rmSync(pngAbs)
    if (existsSync(icoAbs)) rmSync(icoAbs)
    // Report the spawn error and stderr, not just the exit code. A missing binary and a
    // missing display both surface as `status: null`, and without these they are
    // indistinguishable — which is exactly how the Windows failure went undiagnosed.
    const detail = [
      res.error ? `${res.error.code ?? ''} ${res.error.message}`.trim() : '',
      res.signal ? `killed by ${res.signal} (timed out)` : '',
      (res.stderr?.toString() ?? '').trim().split('\n').slice(-3).join('\n      '),
    ].filter(Boolean)
    console.warn(
      `  ! could not rasterize ${pngRel}/${icoRel} (exit ${res.status}).\n` +
        `    The app icon falls back to Electron's default; nothing else is affected.\n` +
        `    On headless Linux this needs a display: \`xvfb-run -a pnpm brand\`.` +
        (detail.length ? `\n      ${detail.join('\n      ')}` : '')
    )
  }
}

// ---------------------------------------------------------------------------

function main() {
  const branded = existsSync(MASTER)
  console.log(
    branded
      ? 'Applying InfoAnalytica branding from ia_assets/logo.svg'
      : 'ia_assets/logo.svg not found — writing neutral placeholders instead.\n' +
        'This is expected in a public clone. Drop the lockup in and re-run to brand it.'
  )

  if (!branded) {
    for (const key of ['appFullLight', 'docsFullLight']) write(OUT[key], placeholder({ width: 246, height: 42, dark: false, label: 'logo' }))
    for (const key of ['appFullDark', 'docsFullDark']) write(OUT[key], placeholder({ width: 246, height: 42, dark: true, label: 'logo' }))
    for (const key of ['appIconLight', 'docsIconLight', 'appFavicon', 'docsFavicon']) write(OUT[key], placeholder({ width: 42, height: 42, dark: false }))
    for (const key of ['appIconDark', 'docsIconDark']) write(OUT[key], placeholder({ width: 42, height: 42, dark: true }))
    write(OUT.desktopIconSvg, placeholder({ width: 1024, height: 1024, dark: false }))
    rasterize(OUT.desktopIconSvg, OUT.desktopIconPng, OUT.desktopIconIco)
    return
  }

  const master = parseMaster()
  const full = (dark) =>
    build(master, {
      indices: [...GROUPS.mark, ...GROUPS.wordmark],
      width: 246,
      height: 42,
      dark,
      note: `Horizontal lockup, ${dark ? 'dark' : 'light'} grounds. Mark + wordmark, no tagline.`,
    })
  const icon = (dark) =>
    build(master, {
      indices: GROUPS.mark,
      width: 42,
      height: 42,
      dark,
      note: `Mark alone, ${dark ? 'dark' : 'light'} grounds. The mark is an exact 42x42 square.`,
    })

  const fullLight = full(false), fullDark = full(true)
  const iconLight = icon(false), iconDark = icon(true)

  write(OUT.appFullLight, fullLight)
  write(OUT.appFullDark, fullDark)
  write(OUT.appIconLight, iconLight)
  write(OUT.appIconDark, iconDark)
  write(OUT.appFavicon, iconLight)
  write(OUT.docsFullLight, fullLight)
  write(OUT.docsFullDark, fullDark)
  write(OUT.docsIconLight, iconLight)
  write(OUT.docsIconDark, iconDark)
  write(OUT.docsFavicon, iconLight)
  write(OUT.desktopIconSvg, desktopIcon(master))
  rasterize(OUT.desktopIconSvg, OUT.desktopIconPng, OUT.desktopIconIco)
}

try {
  main()
} catch (err) {
  console.error(`\napply-brand failed: ${err.message}`)
  process.exit(1)
}
